language: java
sudo: false

dist: trusty

jdk:
- oraclejdk8

before_install:
- echo "Install Zookeeper 3.5.4-beta"
  && wget http://archive.apache.org/dist/zookeeper/zookeeper-3.5.4-beta/zookeeper-3.5.4-beta.tar.gz
  && tar -zxf zookeeper-3.5.4-beta.tar.gz
  && mv zookeeper-3.5.4-beta/conf/zoo_sample.cfg zookeeper-3.5.4-beta/conf/zoo.cfg
  && /bin/bash zookeeper-3.5.4-beta/bin/zkServer.sh start

install:
- mvn clean install -DskipTests -B -V
- mvn test

script:
- sh ./tools/check_format.sh

after_success:
- bash <(curl -s https://codecov.io/bash)